name: 'actions-lsb'
description: 'Key/value store for workflow Last Successful Build'
inputs:
  operation:
    description: 'get or put'
    required: true
  ownerRepo:
    description: 'owner/repository name, ex: onshape/ios'
    required: true
  workflowBranch:
    description: 'workflow and branch, ex: ios-demo-c-test/rel-1.126'
    required: true
  putLsb:
    description: 'put operation - required: lsb SHA'
  putVersionWithBuild:
    description: 'put operation - required: lsb version with build'
  expiryMons:
    description: 'put operation - optional: item expiry in months (TTL)'
    default: 12
outputs:
  getLsb:
    description: "get operation only: lsb SHA"
    value: ${{ steps.get.outputs.value }}
  getVersionWithBuild:
    description: "get operation only: lsb version with build"
    value: ${{ steps.get.outputs.version_with_build }}

runs:
  using: "composite"
  steps:
    - name: Operation
      id: get
      run: >
        ${{ github.action_path }}/action.bash
        "${{ inputs.operation }}"
        "${{ inputs.ownerRepo }}"
        "${{ inputs.workflowBranch }}"
        "${{ inputs.putLsb }}"
        "${{ inputs.putVersionWithBuild }}"
        "${{ inputs.expiryMons }}"
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_REGION: us-west-2
        TABLE_NAME: actions-lsb
      shell: bash
